# -*- coding: utf-8 -*-
"""Copy of ml_project _movie Recommondetion system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZ2fVq4LKu9Bsy8uHUaS1mq9aw1DKKMC
"""

!pip install nltk

import numpy as np
import pandas as pd

movie = pd.read_csv('/content/tmdb_5000_movies.csv')
credit = pd.read_csv('/content/tmdb_5000_credits.csv')

movie=pd.read_csv("/content/tmdb_5000_movies.csv")
movie.shape

movie.head()



movie.shape

credit.shape

# merged movie and credit csv togather
movies = movie.merge(credit,on='title')

#checking merge csv shape
movies.shape

movies.sample()

movies.info()

# columns we are keeping
# we have to create tags for the recomonder

# budget=droping it because liking and disliking of movie not depend on how many money used on movie
# genres	= keeping it,recomonding depneds on geners llike somelike comedy horror scifi
# homepage= droping it not neede for recomondation and for create tags
# id= kepping it in  movie poster we need id
# keywords=keeping it,keyword is tags
# original_language=95% of data is eng it will not help us for recomindation
# overview	=we are working on content similarity here so of overview is same then we find similarity in movies it helpful for recomondation
# popularity=droping it here oue applroch is to create tags it will no help so drop
# production_companies	= so we recommon some movie on gener direactor actor on production company made it
# production_countries=  is the movie matters more than the country
# release_date=realeaced date will not inpact recomondation
# revenue= it will not help in recomondation and in tags
# runtime= hours or movie is not imp stroy of the movie imp
# spoken_languages=droping it
# status= not taht important when will movie relace
# tagline= droping not give proper info and oriview will fill the place of this
#  title= we are alredy keeping the orignal_title  of the movie so it not need
# vote_avrage =we are dropiing it
# vote-count=droping it not neede
# movie_id=alrady have id column so droping it
# cast= keeping it so it PEOPLE IS DECIDE ON WHICH ACTOR IS performing in the movie
# crew= people like secific direactor movie so director name in crew so kepping it

# checking
movies['original_language'].value_counts() #here find shape of csv =4809 and 4510=movies are in eng laguage so 95% of data is eng original_language it will not help

# geners
# id
# keywords
# title
# overview
# cast
# crew    keeping this columns

movies=movies[['genres','movie_id','keywords','title','overview','cast','crew']]

movies.head()

# checking missing data
movies.isnull().sum()

# overview has 3 nullvalue so we are droping that rows which have null values

movies.dropna(inplace=True)

movies.isna().sum() # no null values

# checking duplicate values
movies.duplicated().sum()  # no duplicate values

movies.iloc[0].genres

#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# want to convert this format into this
#['action',Advaenture, fantacy,'scifi]

def convert(obj):
  L=[]                                 # name value append here (L=create empty list and by append value stored here)
  for i in ast.literal_eval(obj):     # converting string into list
    L.append(i['name'])               # want to take name value from {"id": 28, "name": "Action"}
  return  L

# all the values are string to convert it into list using 'ast
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

)

# apply conver fun on genres
movies['genres']=movies['genres'].apply(convert)

# apply conver fun on keywords

movies['keywords']=movies['keywords'].apply(convert)

movies['cast'][0] # want first three dictonary needed want top 3 actors

def convert3(obj):
  L=[]                                # name value append here (L=create empty list and by append value stored here)
  counter=0                           # taking counter=0
  for i in ast.literal_eval(obj):    # converting string into list
       if counter !=3:                   # if counter is not equal to 3
           L.append(i['name'])          # append the name in L=[] list
           counter+=1                   # add 1 to counter repet al until counter !=3
       else:                            # if counter =3 the break return l
        break               # want to take name value from {"id": 28, "name": "Action"}
  return  L

# convert3 applying  on  movies['cast]
movies['cast']=movies['cast'].apply(convert3)

movies['crew'][0] # need director name only

def fetch_director(obj):
  L=[]                                    # name value append here (L=create empty list and by append value stored here)
  for i in ast.literal_eval(obj):         # converting string into list
      if i['job']=='Director':            # if i[job] value is direactor then
           L.append(i['name'])             # append the name to the L list then break it
           break
  return L

movies['crew']=movies['crew'].apply(fetch_director)

# this values is in also string form
movies['overview'][0]

# converting these string into list
movies['overview']=movies['overview'].apply(lambda x:x.split())

movies.head()

movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

# it remove the space Science Fiction become ScienceFiction

# Sam Worthington == SamWorthington we have the join the name and surname as the model will
# not get confused as he take sam as diffrent and worthington as two diff person
# if other person sam name diffrant suraname but model this that sam is the  Sam Worthington

movies.head()

# connecting all the columns

movies['tags']=movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

movies.head()

new_df=movies[['movie_id','title','tags']]

new_df=new_df

new_df.info()

# converting  tag which in list converting it into string
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

new_df.head()

new_df['tags'][0] # first row of new_df[tag]

new_df['tags'][1]

\
# making it into lower case
new_df['tags'].apply(lambda x:x.lower())

# we are going to convert text----> vectors by using= text vectorisation

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words='english')

"""max_features=5000:
Limits the vocabulary to the top 5000 most frequent words in the dataset.helps
reduce dimensionality and remove rare words.

stop_words='english':
Removes common English stop words like "the", "is", "and", etc.,
"""

# fit transform CountVectorizer
vectors=cv.fit_transform(new_df['tags']).toarray()

vectors[0]

# most frequat 5000 words we can see by this
cv.get_feature_names_out()

# here are some words like access dancing danced and dance all three have same meaning so this type of thing we have to avoid so we can do here
# is steaming it will write dance,dance and dance for all

# using steaming (installed nltk)

from nltk.stem import PorterStemmer
ps=PorterStemmer()

def stem(text):
  y=[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

ps.stem('dancing')

# checking how def stem works

stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

new_df['tags']=new_df['tags'].apply(stem)

# now every movie converted into vectors

# now we have 4806 vectors i.e movies became vectors and each vector have 500o numbers
# every movie is vector

# now we are going to find distance between two movie id distance less the A movies are sililar
#  if distance is more then its not similer

# we are going to find cosine distance that is angle between them
# why we are doing it when working on high dimentional data we use cosine distance i.e angle between them

from sklearn.metrics.pairwise import cosine_similarity      # if 1 then similarty is more if 0 then similatity is less

similarity=cosine_similarity(vectors)

# how it worls it lets take 1st movie it check similarity of first movie with all of the 4806 i.e all movies
# same for 2nd check similartity of 2nd with 3rd forth finfth till 4806 movie
# if we check sililarity of 2nd movie with 2nd movie both are sam esame so score will be 1 i.e high score

# sorted(similarity[0]) # it  5 similar values 1st  index position not seen here
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

#

def recommend(movie):
  movie_index=new_df[new_df['title']==movie].index[0]
  distance=similarity[movie_index]
  movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6] # x:x its menst sorting on second no not1st

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

"""  movie_index=new_df[new_df['title']==movie].index[0]

You're looking for the row number of the movie you typed.

Example: If you typed "Inception", and it's at row 10 in your data, movie_index will be 10.


distance = similarity[movie_index]
This gets a list of similarity scores between "Inception" and all other movies.

Think of it like:distance = [1.0, 0.9, 0.8, 0.3, 0.95, ...]
1.0 means perfect match (the movie itself).

Other numbers show how similar other movies are (higher = more similar).

movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x: x[1])[1:6]

orted(..., reverse=True) sorts them from most to least similar.high sililariy score to low

[1:6] skips the first (which is the movie itself) and keeps the next 5.
for i in movies_list:
    print(new_df.iloc[i[0]]['title'])
i[0] is the index of the recommended movie.

You print the title of each one.
"""

\
# featch index
#new_df[new_df['title']=='Batman Begins'].index[0]

recommend('Batman Begins')

# pickle
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

new_df['title'].values



pickle.dump(similarity,open('similarity.pkl','wb'))